name: tests

on:
  pull_request:
    branches: [main]
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
  workflow_dispatch:

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: test Python ${{ matrix.python }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: Agg
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        is_main:
          - ${{ contains(github.ref, 'main') }}
        exclude:
          - is_main: false
            python: "3.10"
          - is_main: false
            python: "3.11"
          - is_main: false
            python: "3.12"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached environment
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          key:
            test-${{ matrix.os }}-py${{ matrix.python }}-${{ hashFiles('tox.ini', 'pyproject.toml', '.github/workflows/tests') }}
          path: |
            ~/.cache
            ~/.tox

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: python -m pip install tox

      - name: Setup test environment
        run: tox -vv --notest -e ${{ matrix.python }}

      - name: Cache environment
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          key:
            ${{ steps.cache-restore.outputs.cache-primary-key }}
          path: |
            ~/.cache
            ~/.tox

      - name: Run test
        run: tox --skip-pkg-install -e ${{ matrix.python }}

      - name: Upload coverage reports to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  minimum-requirements:
    name: minimum requirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached environment
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          key:
            test-minreq-${{ matrix.os }}-py${{ matrix.python }}-${{ hashFiles('tox.ini', 'pyproject.toml', '.github/workflows/tests') }}
          path: |
            ~/.cache
            ~/.tox

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install tox
        run: python -m pip install tox-min-req

      - name: Setup test environment
        run: MIN_REQ=1 tox -vv --notest -e py310

      - name: Cache environment
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          key:
            ${{ steps.cache-restore.outputs.cache-primary-key }}
          path: |
            ~/.cache
            ~/.tox

      - name: Run test
        run: MIN_REQ=1 tox --skip-pkg-install -e py310


  docs:
    name: docs (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached environment
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          key:
            docs-${{ matrix.os }}-py310-${{ hashFiles('tox.ini', 'pyproject.toml', '.github/workflows/tests') }}
          path: |
            ~/.cache
            ~/.tox

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.19.2'

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install tox
        run: python -m pip install tox

      - name: Setup test environment
        run: tox -vv --notest -e docs

      - name: Cache environment
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          key:
            ${{ steps.cache-restore.outputs.cache-primary-key }}
          path: |
            ~/.cache
            ~/.tox

      - name: Run test
        run: tox --skip-pkg-install -e docs

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: html-docs-${{ matrix.os }}
          path: docs/build/
